services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ms_user
      POSTGRES_PASSWORD: ms_pass
      POSTGRES_DB: medisaas_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
